### ISSUE TITLE
Headers being set incorrectly by CorsMiddleware.

### ISSUE THREAD

**Issue by ADmad** [ozee31/cakephp-cors#8]
The CorsMiddleware incorrectly sets response headers first and then calls `$next()`. This causes problem when an exception is thrown; the headers are lost since a new response instance is created by the exception render. To avoid this problem you should set the headers on response instance after calling `$next()`.

**Comment by lpj145** [comment]
i try it, and when middleware call $next first, app stop and not continue runing middleware code.
*** It occur only exception's.

**Comment by bravo-kernel** [comment]
As I pointed out before there is a good example of manipulating after next right here: https://github.com/UseMuffin/Throttle/blob/master/src/Middleware/ThrottleMiddleware.php#L57

**Comment by ADmad** [comment]
[This](https://github.com/tuupola/cors-middleware/blob/master/src/Cors.php#L86) CORS middleware lib also does the same. Gets response instance first by calling `$next()` and then sets the CORS headers.

**Comment by ozee31** [comment]
Thank you for your issue, I look at this ASAP

**Comment by lpj145** [comment]
@ADmad CORS you mentioned not works again, this middleware works all frameworks with PSR7 Middleware, but this not works again, i think this cause by throw, but i don't understand how does it works.

**Comment by eymen-elkum** [comment]
My working case: 
1. I am using `ApiListener` 
2. In `config/app.php`:
````php
    'Error' => [
        'errorLevel' => E_ALL,
        'exceptionRenderer' => 'Crud\Error\ExceptionRenderer',
        'skipLog' => [],
        'log' => true,
        'trace' => true,
    ],
    . . . . . 
    'Cors' => [
        'exceptionRenderer' => false
    ],
````
2. In `config/bootstrap.php`:
````php
Plugin::load('Cors', ['bootstrap' => true, 'routes' => false]);
````
3. In ` src / Controller / ErrorController.php`:
````php
    public function beforeRender(Event $event)
    {
        parent::beforeRender($event);

        //note that I used the deprecated header function
        $this->response->header(['Access-Control-Allow-Origin' => '*']);
        //$this->response->withHeader('Access-Control-Allow-Origin', '*');
        $this->viewBuilder()->setTemplatePath('Error');
    }
````
4. In my `src / Controller / Api / ApiController.php`:
```php
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.ApiPagination',
                'Crud.RelatedModels',
                'Crud.ApiQueryLog'
            ]
        ]);

```
In my case the errors working as expected, but note that I used the deprecated function

**Comment by eymen-elkum** [comment]
@ozee31 I suggest to revert my PR #6  for now

**Comment by ADmad** [comment]
@ayman-alkom The mistake in the readme PR is the result of withHeader() needs to be assigned back to $this->response.

**Comment by eymen-elkum** [comment]
@ADmad how can we do that? like this?
```php
$this->response = $this->response->withHeader('Access-Control-Allow-Origin', '*');
```

**Comment by ADmad** [comment]
Yes.

**Comment by eymen-elkum** [comment]
I may tried it and didn't work, but I will try again

**Comment by ozee31** [comment]
I have fixed `$this->response = $this->response->withHeader('Access-Control-Allow-Origin', '*');` in a new release.

**Comment by bravo-kernel** [comment]
@ozee31 I cannot test because my demo/blog app does not have an `App\Controller\ErrorController` (and thus crashes). Would it be possible to only extend if it exists? Not sure if Cake does this too but SO mentions this possible solution: http://stackoverflow.com/questions/17324871/extend-php-class-only-if-other-class-is-defined.

**Comment by ADmad** [comment]
@ozee31 You should still do the change suggested in my original post.

**Comment by ozee31** [comment]
I am watching

**Comment by bravo-kernel** [comment]
@ozee31 just tested and the release does not fix the problem yet

**Comment by lpj145** [comment]
ok.... i try much options... but no solution... i make new middleware but no solution. My solution is going edit JsonApiException and copy olders responses to new reponses with Exception... i try try try... this is expensive for me. In last week, just doing this.

**Comment by lpj145** [comment]
the problem is throw, if middleware run $next() and found throw, code stop and die with new exception JsonApiException. JsonApiException prepare json.vnd/application but no prepare other headers.

**Comment by eymen-elkum** [comment]
@lpj145 my project is working well, but with the ApiListener and not JsonApiListener.
Try it and tell me if that is working

**Comment by ozee31** [comment]
I have the same problem with the default configuration without using Cors ErrorsController. All my attempts are for the moment a failure with an Exception

**Comment by bravo-kernel** [comment]
This does indeed seem to work with the ApiListener.

First created this empty `App/Controller/ErrorController`:

```php
<?php
namespace App\Controller;

use Cake\Controller\ErrorController as BaseErrorController;

class ErrorController extends BaseErrorController
{
}
```

# ApiListener

> **Update:** False positive, it seemed the image below was not using the ApiListener ExceptionRenderer at all. The response json is produced by default CakePHP fallback.

ApiListener seems to work as expected:

- Access-Control-Allow-Origin header added to the response (OK)
- ApiListener produces JSON response with validation error message (OK)

![afbeelding](https://cloud.githubusercontent.com/assets/230500/25036819/31f1b004-20f6-11e7-8835-23d05c796b66.png)

# JsonApiListener

## First test

Only changing the listener from `ApiListener` to `JsonApiListener`:

- Access-Control-Allow-Origin header added to the response (OK)
- no JSON API response (NOK)

![afbeelding](https://cloud.githubusercontent.com/assets/230500/25037114/8be65e38-20f7-11e7-8a1f-e1ac5a147ef6.png)

## Second test

Changing the ExceptionRenderer in `app.php` to;

```php
    'Cors' => [
        'exceptionRenderer' => '\Crud\Error\JsonApiExceptionRenderer'
    ],
```

- Access-Control-Allow-Origin header is missing from the response (NOK)
- JsonApiListener produces JSON API response with validation error message (OK)

![afbeelding](https://cloud.githubusercontent.com/assets/230500/25037220/25219b76-20f8-11e7-8f8a-b37e7b80fa56.png)

**Comment by bravo-kernel** [comment]
I will try and investigate the JsonApiListener the coming days.

**Comment by ozee31** [comment]
Hey,

Can you test branch https://github.com/ozee31/cakephp-cors/tree/v1.1.0

The Cors ExceptionRenderer extends class dynamicly and add Cors Header. I removed the ErrorController.

in you app.php use :
````PHP
'Error' => [
    'errorLevel' => E_ALL,
    'exceptionRenderer' => 'Crud\Error\ExceptionRenderer', // Or an other
    'skipLog' => [],
    'log' => true,
    'trace' => true,
],

'Cors' => [
    'exceptionRenderer' => 'Cors\Error\AppExceptionRenderer', // not false because add the Header and extend 'Error.execptionRenderer
]

**Comment by lpj145** [comment]
@ozee31 exceptionRenderer needed JsonApiException but not have true data structure.

**Comment by lpj145** [comment]
i try it, but no have body... please, Cors not have problem, JsonApiException works always create new Controller, i debug it and found error with throw.

**Comment by bravo-kernel** [comment]
@lpj145 maybe we can discuss this further on Slack, I see no differences between ApiListener and ApiListener exceptions. These stacktraces were created from inside `Cake\Core\Exception\Exception`, both still having the cors middleware:

## ApiListener stack trace

<details>

```php
<pre class="pr">Crud\Error\Exception\ValidationException Object
(
    [_validationErrors:protected] => Array
        (
            [name] => Array
                (
                    [_empty] => This field cannot be left empty
                )

        )

    [_validationErrorCount:protected] => 1
    [_attributes:protected] => Array
        (
        )

    [_messageTemplate:protected] => 
    [_responseHeaders:protected] => 
    [message:protected] => A validation error occurred
    [string:Exception:private] => 
    [code:protected] => 422
    [file:protected] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/friendsofcake/crud/src/Listener/ApiListener.php
    [line:protected] => 182
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/friendsofcake/crud/src/Listener/ApiListener.php
                    [line] => 121
                    [function] => _exceptionResponse
                    [class] => Crud\Listener\ApiListener
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Cake\Event\Event Object
                                (
                                    [_name:protected] => Crud.beforeRender
                                    [_subject:protected] => Crud\Event\Subject Object
                                        (
                                            [_events:protected] => Array
                                                (
                                                    [0] => Crud.beforeSave
                                                    [1] => Crud.afterSave
                                                    [2] => Crud.setFlash
                                                    [3] => Crud.beforeRender
                                                )

                                            [entity] => App\Model\Entity\Cocktail Object
                                                (
                                                    [description] => None inspired description
                                                    [[new]] => 1
                                                    [[accessible]] => Array
                                                        (
                                                            [name] => 1
                                                            [description] => 1
                                                        )

                                                    [[dirty]] => Array
                                                        (
                                                            [description] => 1
                                                        )

                                                    [[original]] => Array
                                                        (
                                                        )

                                                    [[virtual]] => Array
                                                        (
                                                        )

                                                    [[errors]] => Array
                                                        (
                                                            [name] => Array
                                                                (
                                                                    [_empty] => This field cannot be left empty
                                                                )

                                                        )

                                                    [[invalid]] => Array
                                                        (
                                                            [name] => 
                                                        )

                                                    [[repository]] => Cocktails
                                                )

                                            [saveMethod] => save
                                            [saveOptions] => Array
                                                (
                                                )

                                            [success] => 
                                            [created] => 
                                            [element] => default
                                            [params] => Array
                                                (
                                                    [class] => message error
                                                    [original] => Could not create cocktail
                                                )

                                            [key] => flash
                                            [type] => .error
                                            [name] => cocktail
                                            [text] => Could not create cocktail
                                        )

                                    [_data:protected] => Array
                                        (
                                        )

                                    [result] => 
                                    [_stopped:protected] => 
                                )

                            [1] => Array
                                (
                                    [type] => validate
                                    [class] => \Crud\Error\Exception\ValidationException
                                    [message] => Unknown error
                                    [code] => 0
                                )

                        )

                )

            [1] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/cakephp/cakephp/src/Event/EventManager.php
                    [line] => 414
                    [function] => respond
                    [class] => Crud\Listener\ApiListener
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Cake\Event\Event Object
                                (
                                    [_name:protected] => Crud.beforeRender
                                    [_subject:protected] => Crud\Event\Subject Object
                                        (
                                            [_events:protected] => Array
                                                (
                                                    [0] => Crud.beforeSave
                                                    [1] => Crud.afterSave
                                                    [2] => Crud.setFlash
                                                    [3] => Crud.beforeRender
                                                )

                                            [entity] => App\Model\Entity\Cocktail Object
                                                (
                                                    [description] => None inspired description
                                                    [[new]] => 1
                                                    [[accessible]] => Array
                                                        (
                                                            [name] => 1
                                                            [description] => 1
                                                        )

                                                    [[dirty]] => Array
                                                        (
                                                            [description] => 1
                                                        )

                                                    [[original]] => Array
                                                        (
                                                        )

                                                    [[virtual]] => Array
                                                        (
                                                        )

                                                    [[errors]] => Array
                                                        (
                                                            [name] => Array
                                                                (
                                                                    [_empty] => This field cannot be left empty
                                                                )

                                                        )

                                                    [[invalid]] => Array
                                                        (
                                                            [name] => 
                                                        )

                                                    [[repository]] => Cocktails
                                                )

                                            [saveMethod] => save
                                            [saveOptions] => Array
                                                (
                                                )

                                            [success] => 
                                            [created] => 
                                            [element] => default
                                            [params] => Array
                                                (
                                                    [class] => message error
                                                    [original] => Could not create cocktail
                                                )

                                            [key] => flash
                                            [type] => .error
                                            [name] => cocktail
                                            [text] => Could not create cocktail
                                        )

                                    [_data:protected] => Array
                                        (
                                        )

                                    [result] => 
                                    [_stopped:protected] => 
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/cakephp/cakephp/src/Event/EventManager.php
                    [line] => 391
                    [function] => _callListener
                    [class] => Cake\Event\EventManager
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => Crud\Listener\ApiListener Object
                                        (
                                            [_defaultConfig:protected] => Array
                                                (
                                                    [viewClasses] => Array
                                                        (
                                                            [json] => Json
                                                            [xml] => Xml
                                                        )

                                                    [detectors] => Array
                                                        (
                                                            [json] => Array
                                                                (
                                                                    [ext] => json
                                                                    [accepts] => application/json
                                                                )

                                                            [xml] => Array
                                                                (
                                                                    [ext] => xml
                                                                    [accepts] => text/xml
                                                                )

                                                        )

                                                    [exception] => Array
                                                        (
                                                            [type] => default
                                                            [class] => Cake\Network\Exception\BadRequestException
                                                            [message] => Unknown error
                                                            [code] => 0
                                                        )

                                                    [exceptionRenderer] => Crud\Error\ExceptionRenderer
                                                    [setFlash] => 
                                                )

                                            [_controller:protected] => App\Controller\Api\CocktailsController Object
                                                (
                                                    [paginate] => Array
                                                        (
                                                            [page] => 1
                                                            [limit] => 5
                                                            [maxLimit] => 15
                                                            [sortWhitelist] => Array
                                                                (
                                                                    [0] => name
                                                                    [1] => description
                                                                )

                                                        )

                                                    [name] => Cocktails
                                                    [helpers] => Array
                                                        (
                                                        )

                                                    [request] => Cake\Http\ServerRequest Object
                                                        (
                                                            [params] => Array
                                                                (
                                                                    [pass] => Array
                                                                        (
                                                                        )

                                                                    [controller] => Cocktails
                                                                    [action] => add
                                                                    [_method] => POST
                                                                    [prefix] => api
                                                                    [plugin] => 
                                                                    [_matchedRoute] => /api/cocktails
                                                                    [isAjax] => 
                                                                )

                                                            [data] => Array
                                                                (
                                                                    [name] => 
                                                                    [description] => None inspired description
                                                                )

                                                            [query] => Array
                                                                (
                                                                )

                                                            [cookies] => Array
                                                                (
                                                                )

                                                            [_environment:protected] => Array
                                                                (
                                                                    [USER] => www-data
                                                                    [HOME] => /var/www
                                                                    [HTTP_CONNECTION] => keep-alive
                                                                    [HTTP_CONTENT_LENGTH] => 65
                                                                    [HTTP_ACCEPT_ENCODING] => gzip, deflate
                                                                    [HTTP_HOST] => cake3api.app
                                                                    [HTTP_USER_AGENT] => PostmanRuntime/3.0.11-hotfix.2
                                                                    [HTTP_ORIGIN] => http://www.error-headers.ru
                                                                    [HTTP_CONTENT_TYPE] => application/json
                                                                    [HTTP_ACCEPT] => application/json
                                                                    [HTTP_POSTMAN_TOKEN] => 170fa12c-7239-4120-81c9-6fdb90b0f7a0
                                                                    [HTTP_CACHE_CONTROL] => no-cache
                                                                    [SCRIPT_FILENAME] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/webroot/index.php
                                                                    [REDIRECT_STATUS] => 200
                                                                    [SERVER_NAME] => cake3api.app
                                                                    [SERVER_PORT] => 80
                                                                    [SERVER_ADDR] => 192.168.1.10
                                                                    [REMOTE_PORT] => 64256
                                                                    [REMOTE_ADDR] => 192.168.1.229
                                                                    [SERVER_SOFTWARE] => nginx/1.11.9
                                                                    [GATEWAY_INTERFACE] => CGI/1.1
                                                                    [REQUEST_SCHEME] => http
                                                                    [SERVER_PROTOCOL] => HTTP/1.1
                                                                    [DOCUMENT_ROOT] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/webroot
                                                                    [DOCUMENT_URI] => /index.php
                                                                    [REQUEST_URI] => /api/cocktails
                                                                    [SCRIPT_NAME] => /index.php
                                                                    [CONTENT_LENGTH] => 65
                                                                    [CONTENT_TYPE] => application/json
                                                                    [REQUEST_METHOD] => POST
                                                                    [QUERY_STRING] => 
                                                                    [FCGI_ROLE] => RESPONDER
                                                                    [PHP_SELF] => /index.php
                                                                    [REQUEST_TIME_FLOAT] => 1492185777.5612
                                                                    [REQUEST_TIME] => 1492185777
                                                                    [ORIGINAL_REQUEST_METHOD] => POST
                                                                    [HTTPS] => 
                                                                    [HTTP_X_REQUESTED_WITH] => 
                                                                )

                                                            [url] => api/cocktails
                                                            [base] => 
                                                            [webroot] => /
                                                            [here] => /api/cocktails
                                                            [trustProxy] => 
                                                            [_input:protected] => 
                                                            [_detectorCache:protected] => Array
                                                                (
                                                                    [options] => 
                                                                    [json] => 1
                                                                    [api] => 1
                                                                    [ajax] => 
                                                                    [get] => 
                                                                    [head] => 
                                                                    [post] => 1
                                                                    [put] => 
                                                                )

                                                            [stream:protected] => Zend\Diactoros\PhpInputStream Object
                                                                (
                                                                    [cache:Zend\Diactoros\PhpInputStream:private] => {
  "name": "",
  "description": "None inspired description"
}
                                                                    [reachedEof:Zend\Diactoros\PhpInputStream:private] => 1
                                                                    [resource:protected] => Resource id #5
                                                                    [stream:protected] => php://input
                                                                )

                                                            [uri:protected] => Zend\Diactoros\Uri Object
                                                                (
                                                                    [allowedSchemes:protected] => Array
                                                                        (
                                                                            [http] => 80
                                                                            [https] => 443
                                                                        )

                                                                    [scheme:Zend\Diactoros\Uri:private] => http
                                                                    [userInfo:Zend\Diactoros\Uri:private] => 
                                                                    [host:Zend\Diactoros\Uri:private] => cake3api.app
                                                                    [port:Zend\Diactoros\Uri:private] => 
                                                                    [path:Zend\Diactoros\Uri:private] => /api/cocktails
                                                                    [query:Zend\Diactoros\Uri:private] => 
                                                                    [fragment:Zend\Diactoros\Uri:private] => 
                                                                    [uriString:Zend\Diactoros\Uri:private] => 
                                                                    [base] => 
                                                                    [webroot] => /
                                                                )

                                                            [session:protected] => Cake\Network\Session Object
                                                                (
                                                                    [_engine:protected] => 
                                                                    [_started:protected] => 
                                                                    [_lifetime:protected] => 1440
                                                                    [_isCLI:protected] => 
                                                                )

                                                            [attributes:protected] => Array
                                                                (
                                                                )

                                                            [emulatedAttributes:protected] => Array
                                                                (
                                                                    [0] => session
                                                                    [1] => webroot
                                                                    [2] => base
                                                                    [3] => params
                                                                )

                                                            [uploadedFiles:protected] => Array
                                                                (
                                                                )

                                                            [protocol:protected] => 
                                                            [requestTarget:protected] => 
                                                        )

                                                    [response] => Cake\Http\Response Object
                                                        (
                                                            [status] => 200
                                                            [contentType] => text/html
                                                            [headers] => Array
                                                                (
                                                                    [Content-Type] => Array
                                                                        (
                                                                            [0] => text/html; charset=UTF-8
                                                                        )

                                                                    [Access-Control-Allow-Origin] => Array
                                                                        (
                                                                            [0] => http://www.error-headers.ru
                                                                        )

                                                                    [Access-Control-Allow-Credentials] => Array
                                                                        (
                                                                            [0] => true
                                                                        )

                                                                    [Access-Control-Max-Age] => Array
                                                                        (
                                                                            [0] => 86400
                                                                        )

                                                                )

                                                            [file] => 
                                                            [fileRange] => Array
                                                                (
                                                                )

                                                            [cookies] => Array
                                                                (
                                                                )

                                                            [cacheDirectives] => Array
                                                                (
                                                                )

                                                            [body] => 
                                                        )

                                                    [_responseClass:protected] => Cake\Http\Response
                                                    [autoRender] => 1
                                                    [_components:protected] => Cake\Controller\ComponentRegistry Object
                                                        (
                                                            [_Controller] => App\Controller\Api\CocktailsController Object
 *RECURSION*

        )

    [previous:Exception:private] => 
    [xdebug_message] =>
```
</details>

## JsonApiListener stack trace

<details>

```php
<pre class="pr">Crud\Error\Exception\ValidationException Object
(
    [_validationErrors:protected] => Array
        (
            [name] => Array
                (
                    [_empty] => This field cannot be left empty
                )

        )

    [_validationErrorCount:protected] => 1
    [_attributes:protected] => Array
        (
        )

    [_messageTemplate:protected] => 
    [_responseHeaders:protected] => 
    [message:protected] => A validation error occurred
    [string:Exception:private] => 
    [code:protected] => 422
    [file:protected] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/friendsofcake/crud/src/Listener/ApiListener.php
    [line:protected] => 182
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/friendsofcake/crud/src/Listener/ApiListener.php
                    [line] => 121
                    [function] => _exceptionResponse
                    [class] => Crud\Listener\ApiListener
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Cake\Event\Event Object
                                (
                                    [_name:protected] => Crud.beforeRender
                                    [_subject:protected] => Crud\Event\Subject Object
                                        (
                                            [_events:protected] => Array
                                                (
                                                    [0] => Crud.beforeSave
                                                    [1] => Crud.afterSave
                                                    [2] => Crud.setFlash
                                                    [3] => Crud.beforeRender
                                                )

                                            [entity] => App\Model\Entity\Cocktail Object
                                                (
                                                    [description] => None inspired description
                                                    [[new]] => 1
                                                    [[accessible]] => Array
                                                        (
                                                            [name] => 1
                                                            [description] => 1
                                                        )

                                                    [[dirty]] => Array
                                                        (
                                                            [description] => 1
                                                        )

                                                    [[original]] => Array
                                                        (
                                                        )

                                                    [[virtual]] => Array
                                                        (
                                                        )

                                                    [[errors]] => Array
                                                        (
                                                            [name] => Array
                                                                (
                                                                    [_empty] => This field cannot be left empty
                                                                )

                                                        )

                                                    [[invalid]] => Array
                                                        (
                                                            [name] => 
                                                        )

                                                    [[repository]] => Cocktails
                                                )

                                            [saveMethod] => save
                                            [saveOptions] => Array
                                                (
                                                )

                                            [success] => 
                                            [created] => 
                                            [element] => default
                                            [params] => Array
                                                (
                                                    [class] => message error
                                                    [original] => Could not create cocktail
                                                )

                                            [key] => flash
                                            [type] => .error
                                            [name] => cocktail
                                            [text] => Could not create cocktail
                                        )

                                    [_data:protected] => Array
                                        (
                                        )

                                    [result] => 
                                    [_stopped:protected] => 
                                )

                            [1] => Array
                                (
                                    [type] => validate
                                    [class] => \Crud\Error\Exception\ValidationException
                                    [message] => Unknown error
                                    [code] => 0
                                )

                        )

                )

            [1] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/friendsofcake/crud/src/Listener/JsonApiListener.php
                    [line] => 175
                    [function] => respond
                    [class] => Crud\Listener\ApiListener
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Cake\Event\Event Object
                                (
                                    [_name:protected] => Crud.beforeRender
                                    [_subject:protected] => Crud\Event\Subject Object
                                        (
                                            [_events:protected] => Array
                                                (
                                                    [0] => Crud.beforeSave
                                                    [1] => Crud.afterSave
                                                    [2] => Crud.setFlash
                                                    [3] => Crud.beforeRender
                                                )

                                            [entity] => App\Model\Entity\Cocktail Object
                                                (
                                                    [description] => None inspired description
                                                    [[new]] => 1
                                                    [[accessible]] => Array
                                                        (
                                                            [name] => 1
                                                            [description] => 1
                                                        )

                                                    [[dirty]] => Array
                                                        (
                                                            [description] => 1
                                                        )

                                                    [[original]] => Array
                                                        (
                                                        )

                                                    [[virtual]] => Array
                                                        (
                                                        )

                                                    [[errors]] => Array
                                                        (
                                                            [name] => Array
                                                                (
                                                                    [_empty] => This field cannot be left empty
                                                                )

                                                        )

                                                    [[invalid]] => Array
                                                        (
                                                            [name] => 
                                                        )

                                                    [[repository]] => Cocktails
                                                )

                                            [saveMethod] => save
                                            [saveOptions] => Array
                                                (
                                                )

                                            [success] => 
                                            [created] => 
                                            [element] => default
                                            [params] => Array
                                                (
                                                    [class] => message error
                                                    [original] => Could not create cocktail
                                                )

                                            [key] => flash
                                            [type] => .error
                                            [name] => cocktail
                                            [text] => Could not create cocktail
                                        )

                                    [_data:protected] => Array
                                        (
                                        )

                                    [result] => 
                                    [_stopped:protected] => 
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/cakephp/cakephp/src/Event/EventManager.php
                    [line] => 414
                    [function] => respond
                    [class] => Crud\Listener\JsonApiListener
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Cake\Event\Event Object
                                (
                                    [_name:protected] => Crud.beforeRender
                                    [_subject:protected] => Crud\Event\Subject Object
                                        (
                                            [_events:protected] => Array
                                                (
                                                    [0] => Crud.beforeSave
                                                    [1] => Crud.afterSave
                                                    [2] => Crud.setFlash
                                                    [3] => Crud.beforeRender
                                                )

                                            [entity] => App\Model\Entity\Cocktail Object
                                                (
                                                    [description] => None inspired description
                                                    [[new]] => 1
                                                    [[accessible]] => Array
                                                        (
                                                            [name] => 1
                                                            [description] => 1
                                                        )

                                                    [[dirty]] => Array
                                                        (
                                                            [description] => 1
                                                        )

                                                    [[original]] => Array
                                                        (
                                                        )

                                                    [[virtual]] => Array
                                                        (
                                                        )

                                                    [[errors]] => Array
                                                        (
                                                            [name] => Array
                                                                (
                                                                    [_empty] => This field cannot be left empty
                                                                )

                                                        )

                                                    [[invalid]] => Array
                                                        (
                                                            [name] => 
                                                        )

                                                    [[repository]] => Cocktails
                                                )

                                            [saveMethod] => save
                                            [saveOptions] => Array
                                                (
                                                )

                                            [success] => 
                                            [created] => 
                                            [element] => default
                                            [params] => Array
                                                (
                                                    [class] => message error
                                                    [original] => Could not create cocktail
                                                )

                                            [key] => flash
                                            [type] => .error
                                            [name] => cocktail
                                            [text] => Could not create cocktail
                                        )

                                    [_data:protected] => Array
                                        (
                                        )

                                    [result] => 
                                    [_stopped:protected] => 
                                )

                        )

                )

            [3] => Array
                (
                    [file] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/vendor/cakephp/cakephp/src/Event/EventManager.php
                    [line] => 391
                    [function] => _callListener
                    [class] => Cake\Event\EventManager
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => Crud\Listener\JsonApiListener Object
                                        (
                                            [neomerxPackage:protected] => neomerx/json-api:^0.8.10
                                            [_defaultConfig:protected] => Array
                                                (
                                                    [detectors] => Array
                                                        (
                                                            [jsonapi] => Array
                                                                (
                                                                    [ext] => 
                                                                    [accepts] => application/vnd.api+json
                                                                )

                                                        )

                                                    [exception] => Array
                                                        (
                                                            [type] => default
                                                            [class] => Cake\Network\Exception\BadRequestException
                                                            [message] => Unknown error
                                                            [code] => 0
                                                        )

                                                    [exceptionRenderer] => Crud\Error\JsonApiExceptionRenderer
                                                    [setFlash] => 
                                                    [withJsonApiVersion] => 
                                                    [meta] => Array
                                                        (
                                                        )

                                                    [absoluteLinks] => 
                                                    [jsonApiBelongsToLinks] => 
                                                    [jsonOptions] => Array
                                                        (
                                                        )

                                                    [debugPrettyPrint] => 1
                                                    [include] => Array
                                                        (
                                                        )

                                                    [fieldSets] => Array
                                                        (
                                                        )

                                                    [docValidatorAboutLinks] => 
                                                )

                                            [_controller:protected] => App\Controller\Api\CocktailsController Object
                                                (
                                                    [paginate] => Array
                                                        (
                                                            [page] => 1
                                                            [limit] => 5
                                                            [maxLimit] => 15
                                                            [sortWhitelist] => Array
                                                                (
                                                                    [0] => name
                                                                    [1] => description
                                                                )

                                                        )

                                                    [name] => Cocktails
                                                    [helpers] => Array
                                                        (
                                                        )

                                                    [request] => Cake\Http\ServerRequest Object
                                                        (
                                                            [params] => Array
                                                                (
                                                                    [pass] => Array
                                                                        (
                                                                        )

                                                                    [controller] => Cocktails
                                                                    [action] => add
                                                                    [_method] => POST
                                                                    [prefix] => api
                                                                    [plugin] => 
                                                                    [_matchedRoute] => /api/cocktails
                                                                    [isAjax] => 
                                                                )

                                                            [data] => Array
                                                                (
                                                                    [name] => 
                                                                    [description] => None inspired description
                                                                )

                                                            [query] => Array
                                                                (
                                                                )

                                                            [cookies] => Array
                                                                (
                                                                )

                                                            [_environment:protected] => Array
                                                                (
                                                                    [USER] => www-data
                                                                    [HOME] => /var/www
                                                                    [HTTP_CONNECTION] => keep-alive
                                                                    [HTTP_CONTENT_LENGTH] => 145
                                                                    [HTTP_ACCEPT_ENCODING] => gzip, deflate
                                                                    [HTTP_HOST] => cake3api.app
                                                                    [HTTP_USER_AGENT] => PostmanRuntime/3.0.11-hotfix.2
                                                                    [HTTP_ORIGIN] => http://www.error-headers.ru
                                                                    [HTTP_CONTENT_TYPE] => application/vnd.api+json
                                                                    [HTTP_ACCEPT] => application/vnd.api+json
                                                                    [HTTP_POSTMAN_TOKEN] => fd0cea91-50ca-4059-97bf-a0aa25151276
                                                                    [HTTP_CACHE_CONTROL] => no-cache
                                                                    [SCRIPT_FILENAME] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/webroot/index.php
                                                                    [REDIRECT_STATUS] => 200
                                                                    [SERVER_NAME] => cake3api.app
                                                                    [SERVER_PORT] => 80
                                                                    [SERVER_ADDR] => 192.168.1.10
                                                                    [REMOTE_PORT] => 64124
                                                                    [REMOTE_ADDR] => 192.168.1.229
                                                                    [SERVER_SOFTWARE] => nginx/1.11.9
                                                                    [GATEWAY_INTERFACE] => CGI/1.1
                                                                    [REQUEST_SCHEME] => http
                                                                    [SERVER_PROTOCOL] => HTTP/1.1
                                                                    [DOCUMENT_ROOT] => /home/vagrant/projects/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/webroot
                                                                    [DOCUMENT_URI] => /index.php
                                                                    [REQUEST_URI] => /api/cocktails
                                                                    [SCRIPT_NAME] => /index.php
                                                                    [CONTENT_LENGTH] => 145
                                                                    [CONTENT_TYPE] => application/vnd.api+json
                                                                    [REQUEST_METHOD] => POST
                                                                    [QUERY_STRING] => 
                                                                    [FCGI_ROLE] => RESPONDER
                                                                    [PHP_SELF] => /index.php
                                                                    [REQUEST_TIME_FLOAT] => 1492185690.4594
                                                                    [REQUEST_TIME] => 1492185690
                                                                    [ORIGINAL_REQUEST_METHOD] => POST
                                                                    [HTTPS] => 
                                                                    [HTTP_X_REQUESTED_WITH] => 
                                                                )

                                                            [url] => api/cocktails
                                                            [base] => 
                                                            [webroot] => /
                                                            [here] => /api/cocktails
                                                            [trustProxy] => 
                                                            [_input:protected] => 
                                                            [_detectorCache:protected] => Array
                                                                (
                                                                    [options] => 
                                                                    [jsonapi] => 1
                                                                    [api] => 1
                                                                    [ajax] => 
                                                                    [get] => 
                                                                    [head] => 
                                                                    [post] => 1
                                                                    [put] => 
                                                                )

                                                            [stream:protected] => Zend\Diactoros\PhpInputStream Object
                                                                (
                                                                    [cache:Zend\Diactoros\PhpInputStream:private] => {
  "data": {
    "type": "cocktails",
    "attributes": {
      "name": "",
      "description": "None inspired description"
    }
  }
}
                                                                    [reachedEof:Zend\Diactoros\PhpInputStream:private] => 1
                                                                    [resource:protected] => Resource id #5
                                                                    [stream:protected] => php://input
                                                                )

                                                            [uri:protected] => Zend\Diactoros\Uri Object
                                                                (
                                                                    [allowedSchemes:protected] => Array
                                                                        (
                                                                            [http] => 80
                                                                            [https] => 443
                                                                        )

                                                                    [scheme:Zend\Diactoros\Uri:private] => http
                                                                    [userInfo:Zend\Diactoros\Uri:private] => 
                                                                    [host:Zend\Diactoros\Uri:private] => cake3api.app
                                                                    [port:Zend\Diactoros\Uri:private] => 
                                                                    [path:Zend\Diactoros\Uri:private] => /api/cocktails
                                                                    [query:Zend\Diactoros\Uri:private] => 
                                                                    [fragment:Zend\Diactoros\Uri:private] => 
                                                                    [uriString:Zend\Diactoros\Uri:private] => 
                                                                    [base] => 
                                                                    [webroot] => /
                                                                )

                                                            [session:protected] => Cake\Network\Session Object
                                                                (
                                                                    [_engine:protected] => 
                                                                    [_started:protected] => 
                                                                    [_lifetime:protected] => 1440
                                                                    [_isCLI:protected] => 
                                                                )

                                                            [attributes:protected] => Array
                                                                (
                                                                )

                                                            [emulatedAttributes:protected] => Array
                                                                (
                                                                    [0] => session
                                                                    [1] => webroot
                                                                    [2] => base
                                                                    [3] => params
                                                                )

                                                            [uploadedFiles:protected] => Array
                                                                (
                                                                )

                                                            [protocol:protected] => 
                                                            [requestTarget:protected] => 
                                                        )

                                                    [response] => Cake\Http\Response Object
                                                        (
                                                            [status] => 200
                                                            [contentType] => text/html
                                                            [headers] => Array
                                                                (
                                                                    [Content-Type] => Array
                                                                        (
                                                                            [0] => text/html; charset=UTF-8
                                                                        )

                                                                    [Access-Control-Allow-Origin] => Array
                                                                        (
                                                                            [0] => http://www.error-headers.ru
                                                                        )

                                                                    [Access-Control-Allow-Credentials] => Array
                                                                        (
                                                                            [0] => true
                                                                        )

                                                                    [Access-Control-Max-Age] => Array
                                                                        (
                                                                            [0] => 86400
                                                                        )

                                                                )

                                                            [file] => 
                                                            [fileRange] => Array
                                                                (
                                                                )

                                                            [cookies] => Array
                                                                (
                                                                )

                                                            [cacheDirectives] => Array
                                                                (
                                                                )

                                                            [body] => 
                                                        )

                                                    [_responseClass:protected] => Cake\Http\Response
                                                    [autoRender] => 1
                                                    [_components:protected] => Cake\Controller\ComponentRegistry Object
                                                        (
                                                            [_Controller] => App\Controller\Api\CocktailsController Object
 *RECURSION*
 
        )

    [previous:Exception:private] => 
    [xdebug_message] =>
```
</details>

**Comment by bravo-kernel** [comment]
@ozee31 could you paste the json validation error response you get when running your v1.1.0 branch?

**Comment by bravo-kernel** [comment]
@ozee31 just tested and.... your v1.1.0 solves the problem 🍰  💃 

![afbeelding](https://cloud.githubusercontent.com/assets/230500/25052851/3a7c7de0-2154-11e7-8133-3cb90541343f.png)

Working `app.php` config for JsonApiListener:

```php
    'Error' => [
        'errorLevel' => E_ALL & ~E_DEPRECATED,
        'exceptionRenderer' => 'Crud\Error\JsonApiExceptionRenderer',
        'skipLog' => [],
        'log' => true,
        'trace' => true,
    ],

    /**
     * Cors required to make sure headers are added on (validation) errors as well.
     */
     'Cors' => [
         'exceptionRenderer' => '\Cors\Error\AppExceptionRenderer'
     ],
```

**Comment by lpj145** [comment]
@ozee31 this works for me. Thanks.

**Comment by bravo-kernel** [comment]
@ozee31 could you please create a new release so I can update blog and close this issue.

**Comment by ozee31** [comment]
Yes i publish new release ASAP

**Comment by ozee31** [comment]
It's released
https://github.com/ozee31/cakephp-cors/releases/tag/v1.1.0

**Comment by bravo-kernel** [comment]
👍
